# https://www.gradle.org/docs/current/userguide/build_environment.html

org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=768M -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx512M -XX:MaxMetaspaceSize=256M -XX:+UseParallelGC

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
